config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :tasks
  end

end

app/models/task.rb
class Task
  include Mongoid::Document
  field :content, type: String
  belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name, type: String
  field :mail, type: String
  field :password, type: String
  field :password_confirm, type: String
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @task = @user.tasks.create![params[:user_id]]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user }
      else
        format.html { redirect_to :new }
      end
    end
  end

  def update
  end

  def destroy
    @user.destroy
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :mail, :password, :password_confirm)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasktable</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :昵称 %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :邮箱 %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :密码 %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :重复密码 %><br>
    <%= f.text_field :password_confirm %>
  </div>
  <div class="actions">
    <%= f.submit '创建用户'%>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>


<%= link_to '注册', new_user_path %>

app/views/users/new.html.erb
<h1>新用户</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>name:</strong>
  <%= @user.name %>
</p>

<h2>new task</h2>
<%= form_for [@user, Task.new] do |f| %>
  <p><%= f.text_area :content, :rows => 10 %></p>
  <p><%= f.submit %></p>
<% end %>